# Generated by Django 3.0.8 on 2020-08-27 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('desc', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(blank=True, choices=[('IMG', 'Image'), ('AU', 'Audio'), ('VID', 'Video'), ('TXT', 'Text')], max_length=10)),
                ('genre', models.CharField(blank=True, choices=[('ART', 'Art'), ('TECH', 'Technology'), ('FAS', 'Fashion'), ('EDU', 'Education'), ('LIF', 'Lifestyle'), ('BOK', 'Books'), ('MOV', 'Movies'), ('MEM', 'Memes'), ('SHO', 'Shopping'), ('COK', 'Cooking'), ('TRA', 'Travel'), ('MUS', 'Music'), ('BLO', 'Blogging'), ('PHO', 'Photography'), ('PHY', 'Physics'), ('ASP', 'Astrophysics'), ('CS', 'ComputerScience'), ('COD', 'Coding')], max_length=10)),
                ('tags', models.TextField(null=True)),
                ('is_safe', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('explore', models.BooleanField()),
                ('creator', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post_to_report', models.ManyToManyField(blank=True, related_name='post_to_report', to='posts.Post')),
                ('reporting_user', models.ManyToManyField(blank=True, related_name='post_reporting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_to_report', models.ManyToManyField(blank=True, related_name='comment_to_report', to='posts.Comment')),
                ('reporting_user', models.ManyToManyField(blank=True, related_name='comment_reporting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
