# Generated by Django 3.0.8 on 2020-08-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200824_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, default='dummy.png', upload_to='profile_pictures'),
        ),
    ]
