# Generated by Django 3.0.8 on 2020-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following_genres',
            field=models.CharField(blank=True, choices=[('#art', 'Art'), ('#tech', 'Technology'), ('#fashion', 'Fashion'), ('#education', 'Education'), ('#lifestyle', 'Lifestyle'), ('#books', 'Books'), ('#movies', 'Movies'), ('#memes', 'Memes'), ('#shopping', 'Shopping'), ('#cooking', 'Cooking'), ('#travel', 'Travel'), ('#music', 'Music'), ('#blogging', 'Blogging'), ('#photography', 'Photography'), ('#physics', 'Physics'), ('#astrophysics', 'Astrophysics'), ('#computer', 'ComputerScience'), ('#code', 'Coding')], max_length=20),
        ),
    ]
