# Generated by Django 3.0.8 on 2020-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_following_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following_genres',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_genres',
            field=models.ManyToManyField(blank=True, related_name='following_genres', to='accounts.Genre'),
        ),
    ]
