# Generated by Django 3.0.8 on 2020-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200828_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent1',
            field=models.CharField(default='#aab4e4', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accent2',
            field=models.CharField(default='#dfa8b5', max_length=20),
        ),
    ]
