# Generated by Django 3.0.8 on 2020-09-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200828_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='dummy.png', upload_to='profile_pictures'),
        ),
    ]
