# Generated by Django 3.0.8 on 2020-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200902_0557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following_genres',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_genres',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
