# Generated by Django 3.0.8 on 2020-09-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200906_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, default='dummy.png', upload_to='profile_pictures'),
        ),
    ]
