# Generated by Django 3.0.8 on 2020-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200906_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, default='/home/zedway/zedway/media/dummy.png', upload_to='profile_pictures'),
        ),
    ]
