# Generated by Django 3.0.8 on 2020-09-10 03:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200907_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=21), size=21),
        ),
    ]
