# Generated by Django 3.0.8 on 2020-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200910_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_genres',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
