# Generated by Django 3.0.8 on 2020-09-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tag_followers'),
        ('accounts', '0023_remove_userprofile_following_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following_tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='following_tags', to='posts.Tag'),
        ),
    ]
